### ISSUE TITLE
Deprecate or update to Meteor 0.9+?

### ISSUE THREAD

**Issue by dandv** [acreeger/meteor-moment#25]
I see that @miraten has updated this package for Meteor 0.9+

https://github.com/miraten/meteor-moment

**Comment by splendido** [comment]
@dandv, do you think we should use our moderators super power on atmosphere to flag this package to make it disappear for good?

**Comment by dandv** [comment]
@splendido: I've just flagged it again, can you flag it as well? Not sure my flag was enough, maybe because of how many downloads it has?
