### ISSUE TITLE
Is global export still needed?

### ISSUE THREAD

**Issue by bradvogel** [acreeger/meteor-moment#26]
Is https://github.com/acreeger/meteor-moment/blob/master/export-moment.js still needed? It's leaking 'moment' in global namespace.

**Comment by splendido** [comment]
It seems this package is no more maintained...
Please refer to the currently up to date [momentjs:moment](https://atmospherejs.com/momentjs/moment)!

**Comment by splendido** [comment]
See also #25

**Comment by dandv** [comment]
:+1:

**Comment by splendido** [comment]
@dandv it seems there are still other xxx:moment packages we should chase ;-)
