### ISSUE TITLE
Reactive-Publish package question

### ISSUE THREAD

**Issue by centinel3** [acreeger/meteor-moment#27]
I apologize for posting here, though didn't see a git repo for the Reactive Publish package built by MRT. Where would I go to report an issue with that package? Any help would be appreciated. Thansk in advance.

Sincerely,
Chris Campbell
centinel3@gmail.com

**Comment by dandv** [comment]
Please use the [official package](https://github.com/acreeger/meteor-moment/pull/23#issuecomment-118940256) instead :)
