### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by robwatkin** [acreeger/meteor-moment#28]
I can't seem to get locale 'en-gb' working so that dates default to DD/MM/YYYY but the files seem to be missing. Looking in the packages folder (Chrome inspect source) the locales files are not listed. 

Following momentjs docs I have tried (as an example), in Chrome inspect 

> moment.locale('fr')
< "en"
> moment(1316116057189).fromNow()
< "3 years ago"
> moment().locale('fr')
< Moment {_isAMomentObject: true, _isUTC: false, _pf: Object, _locale: null, _d: Fri Mar 13 2015 11:58:46 GMT+0000 (GMT)…}
> moment().locale()
< "en"
> moment(1316116057189).fromNow()
< "3 years ago"

**Comment by dandv** [comment]
Please use the [official package](https://github.com/acreeger/meteor-moment/pull/23#issuecomment-118940256) instead :)

**Comment by robwatkin** [comment]
Thanks @dandv
