### ISSUE TITLE
Hide package in favor of momentjs:moment

### ISSUE THREAD

**Issue by zimme** [acreeger/meteor-moment#29]
Maybe `meteor admin set-unmigrated mrt:moment` to hide this package should be done. `momentjs:moment` is the new "official" package which moment publishes.

**Comment by zimme** [comment]
It will still be usable by people new people just won't find it on atmosphere and when doing a `meteor search`

**Comment by dandv** [comment]
:+1: 

Thanks @zimme!

https://github.com/acreeger/meteor-moment/pull/23#issuecomment-118940256
