### ISSUE TITLE
I18n with Meteor 0.6.6

### ISSUE THREAD

**Issue by alesvaupotic** [acreeger/meteor-moment#4]
Is it just me or is moment.lang() not switching languages correctly? 
<pre>
 if (moment) {
  	moment.lang('sl');
    return moment(datetime).fromNow()+" "+moment.lang();
  }
</pre>

returns
<pre>
Friday 11.10.2013 19:57 a few seconds ago en
</pre>

Probably not including the lang files from package?

**Comment by almogdesign** [comment]
I'm not a fan of having to use environment vars. I would prefer to manually add the required lang files into my app compatibility folder. However this isn't working either. I'm going to try the official Meteor Moment package and see if that works 

![screen shot 2015-01-10 at 2 08 16 am](https://cloud.githubusercontent.com/assets/169507/5689457/d4b09efe-986d-11e4-8d31-5a6ca1531b59.png)
